# ============================================================
#  Oklahoma Mesonet Station Registry
#
#  ~121 active stations, each with a 4-char code and city name.
#  Source: https://www.mesonet.org/about/mesonet-sites
# ============================================================

from __future__ import annotations

# Station code -> city/site name
STATIONS: dict[str, str] = {
    "ACME": "Acme",
    "ADAX": "Ada",
    "ALTU": "Altus",
    "ALV2": "Alva",
    "ANTL": "Antlers",
    "APAC": "Apache",
    "ARDM": "Ardmore",
    "ARNE": "Arnett",
    "BEAV": "Beaver",
    "BESS": "Bessie",
    "BIXB": "Bixby",
    "BLAC": "Blackwell",
    "BOIS": "Boise City",
    "BREC": "Breckinridge",
    "BRIS": "Bristow",
    "BROK": "Broken Bow",
    "BUFF": "Buffalo",
    "BURB": "Burbank",
    "BURN": "Burneyville",
    "BUTL": "Butler",
    "BYAR": "Byars",
    "CAMA": "Camargo",
    "CARL": "Lake Carl Blackwell",
    "CENT": "Centrahoma",
    "CHAN": "Chandler",
    "CHER": "Cherokee",
    "CHEY": "Cheyenne",
    "CHIC": "Chickasha",
    "CLAY": "Clayton",
    "CLOU": "Cloudy",
    "COOK": "Cookson",
    "COPA": "Copan",
    "DURA": "Durant",
    "ELKC": "Elk City",
    "ELRE": "El Reno",
    "ERIC": "Erick",
    "EUFA": "Eufaula",
    "EVAX": "Eva",
    "FAIR": "Fairview",
    "FITT": "Fittstown",
    "FORA": "Foraker",
    "FREE": "Freedom",
    "FTCB": "Fort Cobb",
    "GOOD": "Goodwell",
    "GRAN": "Grandfield",
    "GUTH": "Guthrie",
    "HASK": "Haskell",
    "HECT": "Hectorville",
    "HINT": "Hinton",
    "HOBA": "Hobart",
    "HOLD": "Holdenville",
    "HOLL": "Hollis",
    "HOOK": "Hooker",
    "HUGO": "Hugo",
    "IDAB": "Idabel",
    "INOL": "Inola",
    "JAYX": "Jay",
    "KENT": "Kenton",
    "KETC": "Ketchum Ranch",
    "KIN2": "Kingfisher",
    "LAHO": "Lahoma",
    "LANE": "Lane",
    "MADI": "Madill",
    "MANG": "Mangum",
    "MARE": "Marena",
    "MAYR": "May Ranch",
    "MCAL": "McAlester",
    "MEDF": "Medford",
    "MEDI": "Medicine Park",
    "MIAM": "Miami",
    "MINC": "Minco",
    "MRSH": "Marshall",
    "NEWK": "Newkirk",
    "NEWP": "Newport",
    "NOWA": "Nowata",
    "NRMN": "Norman",
    "OILT": "Oilton",
    "OKCE": "OKC East",
    "OKEM": "Okemah",
    "OKMU": "Okmulgee",
    "PAUL": "Pauls Valley",
    "PAWN": "Pawnee",
    "PERK": "Perkins",
    "PORT": "Porter",
    "PRYO": "Pryor",
    "PUTN": "Putnam",
    "REDR": "Red Rock",
    "RING": "Ringling",
    "SALL": "Sallisaw",
    "SEIL": "Seiling",
    "SEMI": "Seminole",
    "SHAW": "Shawnee",
    "SKIA": "Skiatook",
    "SLAP": "Slapout",
    "SPEN": "Spencer",
    "STIG": "Stigler",
    "STIL": "Stillwater",
    "STUA": "Stuart",
    "SULP": "Sulphur",
    "TAHL": "Tahlequah",
    "TALI": "Talihina",
    "TIPT": "Tipton",
    "TISH": "Tishomingo",
    "TULL": "Tulsa",
    "VINI": "Vinita",
    "WALT": "Walters",
    "WASH": "Washington",
    "WATO": "Watonga",
    "WAUR": "Waurika",
    "WEAT": "Weatherford",
    "WEST": "Westville",
    "WILB": "Wilburton",
    "WIST": "Wister",
    "WOOD": "Woodward",
    "WYNO": "Wynona",
}


def station_display_list() -> list[str]:
    """Return sorted list of 'CODE - CityName' strings for GUI combobox."""
    return sorted(f"{code} - {name}" for code, name in STATIONS.items())


def parse_station_code(display: str) -> str:
    """Extract the 4-char station code from a display string like 'NRMN - Norman'."""
    return display.split(" - ", 1)[0].strip().upper()
